
INSERT INTO SHOPPINGLISTS (ID, NAME, STATUS) VALUES ('1', 'Kolacja przy świecach', '0');
INSERT INTO SHOPPINGLISTS (ID, NAME, STATUS) VALUES ('2', 'Wizyta Rodziców', '0');
INSERT INTO SHOPPINGLISTS (ID, NAME, STATUS) VALUES ('3', 'Dieta Ani', '0');
INSERT INTO SHOPPINGLISTS (ID, NAME, STATUS) VALUES ('4', 'Pizza', '0');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('1', 'Pieczarki', '800', 'gram', '4');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('2', 'Salami', '12', 'plastrów', '4');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('3', 'Ser Mozzarella', '150', 'gram', '4');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('4', 'Drożdże', '1', 'szt.', '4');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('5', 'Mąka', '1', 'szt.', '4');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('6', 'Sos pomidorowy', '1', 'szt.', '4');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('7', 'Pomidory', '10', 'szt.', '3');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('8', 'Pomarańcza', '10', 'szt', '3');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('9', 'Płatki owsiane', '1', 'szt.', '3');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('10', 'Jogurt Naturalny', '5', 'szt.', '3');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('11', 'Sałata lodowa', '2', 'szt', '3');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('12', 'Szynka', '10', 'plastrów', '3');
INSERT INTO PRODUCTS (ID, NAME, AMOUNT, UNIT, SHOPPINGLISTS_ID) VALUES ('13', 'Ogórek zielony', '4', 'szt.', '3');